### ISSUE TITLE
Canonicalizing array comparator leaks notices

### ISSUE THREAD

**Issue by JKingweb** [sebastianbergmann/comparator#79]
```php
class TestTest extends \PHPUnit\Framework\TestCase {
    public function testEmitNotice(): void {
        $exp = [1, new \stdClass];
        $act = [1, new \stdClass];
        $this->assertEqualsCanonicalizing($exp, $act);
    }
}
```

```
PHPUnit 9.0.1 by Sebastian Bergmann and contributors.

PHP Notice:  Object of class stdClass could not be converted to int in ./vendor/sebastian/comparator/src/ArrayComparator.php on line 49
PHP Notice:  Object of class stdClass could not be converted to int in ./vendor/sebastian/comparator/src/ArrayComparator.php on line 50
.                                                                   1 / 1 (100%)

Time: 174 ms, Memory: 8.00 MB

OK (1 test, 1 assertion)
```

**Comment by sebastianbergmann** [comment]
I am not sure there is anything that I can do here apart from suppressing the notice. `sort()` simply should not be used on arrays that contain objects.

**Comment by sebastianbergmann** [comment]
This issue is no longer reproducible on the currently supported branches.

The underlying cause (`ArrayComparator` calling `sort()` directly, which falls back to PHP's `<=>` operator and triggers `"Object of class stdClass could not be converted to int"` notices when comparing scalars against objects) was fixed in 2f2fded (which closed #140, a duplicate of this issue). `sort()` was replaced with `usort()` driven by a type-aware comparator that buckets values by type before any `<=>` comparison, so incompatible types never reach the raw operator.

A regression test mirroring the original reproducer has been added in ec4ddf4cef255af75cad979c87b4ecfc2edf378d.
